libsite/libapp/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^(?P<item_id>\d+)/$' , views.detail, name='detail'),
        url(r'^about/$', views.about, name="about"),
        url(r'^suggestions/$', views.suggestions, name="suggestions"),
        url(r'^suggestion/(?P<item_id>\d+)/$', views.suggestion, name="suggestion"),
        url(r'^newitem/$', views.newitem, name="newitem"),
        url(r'^searchlib/$',views.searchlib, name='searchlib'),
        url(r'^login/$',views.user_login,name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^myitem/$', views.myitems, name='myitem'),
        url(r'^forgot/$', views.forgot_password, name='forgot'),
        url(r'^register/$', views.register, name='register'),
        url(r'^success/$', views.success, name='success'),
        url(r'^profile/$', views.profile, name='profile')
        ]

libsite/libsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^libapp/', include('libapp.urls', namespace='libapp')),
    url(r'^admin/', admin.site.urls),
]

libsite/libapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
import os

def get_image_path(instance, filename):
    return os.path.join('libapp/static/libapp/photos', filename)

# Create your models here.
class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    postalcode = models.CharField(max_length=7, null=True, blank=True)
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True)
    profile_image=models.ImageField(upload_to='photos/',default='photos/user.png',blank=True,null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD','DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out=models.BooleanField(default=False)
    user=models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate=models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    num_chkout = models.IntegerField(default=0, null=False, blank=False)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField()

    def overdue(self):
        if self.checked_out == True:
            if self.duedate < datetime.date.today():
                return 'Yes'
            else:
                return 'No'
    overdue.short_description='overdue'

    def __str__(self):
        return self.itemtype + ' : ' + self.title

class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author

class Dvd(Libitem):
    RATING_CHOICE = (
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, '14A'),
        (5, 'R'),
        (6, 'NR'),
    )
    maker = models.CharField(max_length=100)
    duration = models.IntegerField()
    rating = models.IntegerField(choices=RATING_CHOICE,default=1)

    def __str__(self):
        return self.title + ' by ' + self.maker + ' in {0}'.format(self.pubyr)

class Suggestion(models.Model):

    TYPE_CHOICES = (
        (1, 'Book'),
        (2,'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.get_type_display() + ' : ' + self.title

libsite/libapp/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

from libapp.models import Suggestion,Book,Dvd,Libitem,User,Libuser

class SuggestionForm(forms.ModelForm):
    class Meta:
        model=Suggestion
        fields = ['title','pubyr','type','cost','comments']
        widgets = {
            'type':forms.RadioSelect(),
        }
        labels = {
            'pubyr':u'Year of publication',
            'cost':u'Estimated cost in Dollars',
        }

    default_error_messages = {
        'max_length':(u'Ensure this value has at most %(max)d characters (it has %(length)d).'),
        'min_length':(u'Ensure this value has at least %(min)d characters (it has %(length)d).'),
    }
    pubyr=forms.IntegerField(error_messages=default_error_messages,validators=[MaxValueValidator(2016), MinValueValidator(1900)])

class SearchlibForm(forms.ModelForm):
    class Meta:
        model=Libitem
        fields=['title']
    title=forms.CharField(max_length=100,required=False)
    by=forms.CharField(max_length=100,required=False)

class LoginForm(forms.Form):
    class Meta:
        fields=['username','password']
    username=forms.CharField(max_length=100)
    password=forms.CharField(max_length=100,widget=forms.PasswordInput)

class ForgotPasswordForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username']

class RegisterForm(forms.ModelForm):
    class Meta:
        model=Libuser
        fields=['first_name','last_name','email','username','password','address','city','postalcode','province','phone','profile_image']
        widgets={
            'province':forms.Select(),
        }
    first_name = forms.CharField(max_length=30,required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    address = forms.Textarea()
    city = forms.CharField(max_length=30, required=True,initial='Windsor')
    postalcode = forms.CharField(max_length=7, required=False)
    phone=forms.CharField(max_length=11,required=False)
    profile_image=forms.ImageField(required=False)

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Libuser
        fields=['first_name','last_name','email','address','city','postalcode','province','phone','profile_image']
        exclude=['usrname','password']
        widgets = {
            'province': forms.Select(),
        }
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    address = forms.Textarea()
    city = forms.CharField(max_length=30, required=True)
    postalcode = forms.CharField(max_length=7, required=False)
    phone = forms.CharField(max_length=11, required=False)
    profile_image = forms.ImageField(required=False)

libsite/libapp/views.py
import random
from django.core import mail
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User

from libapp.models import Book, Dvd, Libuser, Libitem, Suggestion
from django.shortcuts import get_object_or_404,render
from libapp.forms import SuggestionForm,SearchlibForm,LoginForm,ForgotPasswordForm, RegisterForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                lucky_num=random.randint(1,9)
                request.session['lucky_num'] = lucky_num
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('libapp:index'),{'user':request.user})
            else:
                return render(request,'libapp/login.html',{'msg':'Your account is disabled.'})
        else:
            form = LoginForm()
            return render(request,'libapp/login.html',{'form':form,'msg':'Invalid login details.'})
    else:
        form=LoginForm()
        return render(request, 'libapp/login.html',{'form':form,'msg':''})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('libapp:index')))

def forgot_password(request):
    if request.method == 'POST':
        username=request.POST['username']
        if username=='':
            form = ForgotPasswordForm()
            return render(request, 'libapp/forgot.html',{'form': form, 'msg': 'Please enter username.'})
        try:
            user=User.objects.get(username=username)
            if user:
                password = User.objects.make_random_password()
                user.set_password(password)
                user.save()
                msg='Your password is:'+password
                mail.send_mail(
                    'Password Recovery',
                    msg,
                    '127.0.0.1',
                    [user.email],
                    fail_silently=False,
                )
                return HttpResponseRedirect(reverse('libapp:login'))
                #return render(request, 'libapp/login.html', {'form': form, 'msg': 'Please check your email.'})
                #return user_login(request)
        except User.DoesNotExist:
            form = ForgotPasswordForm()
            return render(request, 'libapp/forgot.html', {'form': form,'msg':'Invalid username. Please contact administrator.'})
    else:
        form=ForgotPasswordForm()
        return render(request, 'libapp/forgot.html', {'form':form,'msg':''})

# Create your views here.
def index(request):
    itemlist = Libitem.objects.all().order_by('title')[:10]
    return render(request, 'libapp/index.html', {'itemlist':itemlist,'user':request.user})

@login_required
def myitems(request):
    user = request.user
    if hasattr(user,'libuser'):
        booklist = Book.objects.filter(checked_out=True).filter(user__username=request.user.username)
        dvdlist = Dvd.objects.filter(checked_out=True).filter(user__username=request.user.username)
        return render(request,'libapp/myitem.html', {'booklist':booklist,'dvdlist':dvdlist,'msg':'','user':user})
    else:
        msg = "You are not a libuser."
        return render(request, 'libapp/myitem.html', {'msg': msg})

def detail(request, item_id):
    item=get_object_or_404(Libitem,id=item_id)
    response = HttpResponse()
    if item.itemtype=='Book':
        data = Book.objects.get(id=item_id)
    else :
        data = Dvd.objects.get(id=item_id)
    return render(request, 'libapp/detail.html', {'item':item,'data':data,'user':request.user})

def about(request):
    visit= int(request.COOKIES.get('about_visits','0'))
    visit = visit + 1
    max_age = 300
    response = render(request, 'libapp/about.html', {'about_visits': visit,'user':request.user})
    response.set_cookie('about_visits', visit, max_age=max_age)
    return response

def suggestions(request):
    suggestionlist = Suggestion.objects.all()[:10]
    return render(request, 'libapp/suggestions.html', {'itemlist': suggestionlist,'user':request.user})

def suggestion(request,item_id):
    suggestion = get_object_or_404(Suggestion,id=item_id)
    return render(request, 'libapp/suggestion_details.html', {'item': suggestion,'user':request.user})

def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect(reverse('libapp:suggestions'))
        else:
            return render(request, 'libapp/newitem.html', {'form': form, 'itemlist': suggestions, 'user':request.user})
    else:
        form = SuggestionForm()
        return render(request, 'libapp/newitem.html', {'form': form, 'itemlist': suggestions,'user':request.user})

def searchlib(request):
    if request.method == 'POST':
        form = SearchlibForm(request.POST)
        if request.POST.get("title")!='':
            booklist=Book.objects.filter(title__contains=request.POST.get("title"))
            dvdlist = Dvd.objects.filter(title__contains=request.POST.get("title"))
            if request.POST.get("by")!='':
                booklist = booklist.filter(author__contains=request.POST.get("by"))
                dvdlist = dvdlist.filter(maker__contains=request.POST.get("by"))
            return render(request, 'libapp/searchlib.html', {'form': form,'booklist':booklist,'dvdlist':dvdlist,'user':request.user})
        elif request.POST.get("by")!='':
            booklist=Book.objects.filter(author__contains=request.POST.get("by"))
            dvdlist = Dvd.objects.filter(maker__contains=request.POST.get("by"))
            return render(request, 'libapp/searchlib.html', {'form': form,'booklist':booklist,'dvdlist':dvdlist,'user':request.user})
        else:
            return render(request, 'libapp/searchlib.html', {'form': form,'user':request.user})
    else:
        form = SearchlibForm()
        return render(request, 'libapp/searchlib.html', {'form': form,'user':request.user})

def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            register = form.save(commit=False)
            register.set_password(request.POST['password'])
            register.save()
            return HttpResponseRedirect(reverse('libapp:success'))
        else:
            return render(request, 'libapp/register.html', {'form': form,'user':request.user})
    else:
        form = RegisterForm()
        return render(request, 'libapp/register.html',{'form':form,'user':request.user})

def success(request):
    return render(request, 'libapp/success.html',{'user':request.user})

@login_required
def profile(request):
    user_info = User.objects.get(username=request.user.username)
    if request.method=="POST":
        form=ProfileForm(request.POST, instance=user_info)
        if form.is_valid():
            form.save()
    form=ProfileForm(instance=user_info)
    return render(request, 'libapp/profile.html',{'profile':user_info,'form':form,'user':request.user})

libsite/libapp/templates/libapp/about.html
{% extends 'libapp/base.html' %}
{% block title %}
    About
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <h2>This is a Library APP.</h2>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-3"></div>

            <div class="col-md-6"><span class="badge bg-primary"> Visits : {{ about_visits }}</span></div>
        </div>

    </div>
{% endblock %}

libsite/libapp/templates/libapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-3.3.6-dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libapp/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-11 h1">MAC Library</div>

				<div class="tools-bar">
						<ul class="nav navbar-nav tooltip-area">
								<li class="dropdown">
                                                                    <a href="#">
											<em>Hello <strong>{% if user.is_authenticated %} {{ user.first_name }} {% else %} User {%  endif %}</strong></em>
										</a>
								</li>

						</ul>
				</div>
        </div>

    </div>
    <hr />
    <nav class="container navbar">
        <ul class="nav nav-pills bg-warning">
            <li><a href = "{% url 'libapp:index' %}">Home</a></li>
            <li><a href="/libapp/about/">About</a></li>
            <li><a href="{% url 'libapp:suggestions' %}">Suggestions</a></li>
            <li><a href="{% url 'libapp:searchlib' %}">Search</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'libapp:myitem' %}">My Items</a></li>
                <li><a href="{% url 'libapp:profile' %}">Profile</a></li>
                <li><a href="{% url 'libapp:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'libapp:register' %}">Register</a></li>
                <li><a href="{% url 'libapp:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}*** {% endblock %}
    </div>

</body>
</html>

libsite/libapp/templates/libapp/detail.html
{% extends 'libapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <h2>Library Item : {{ item.itemtype }}</h2>
    </div>
        <div class="row">
            <div class="panel panel-primary col-sm-12 ">
                <div class="panel-body">
        {% if item.itemtype == 'Book' %}
            <p class="col-md-12">
                <div class="row">
                <div class="col-md-3"> Title : </div><div class="col-md-3"> {{ item.title }} </div></div>
                <div class="row"><div class="col-md-3">Due Date : </div><div class="col-md-3">{% if item.duedate != none %}{{ item.duedate }}{% else %} - {% endif %}</div></div>
                <div class="row"><div class="col-md-3">Author : </div><div class="col-md-3">{{ data.author }} </div></div>
                <div class="row"><div class="col-md-3">Category : </div><div class="col-md-3">{{ data.get_category_display }} </div></div>
            </p>
        {% else %}
            <p class="col-md-12">
                <div class="row"><div class="col-md-3"> Title : </div><div class="col-md-3"> {{ item.title }} </div></div>
                <div class="row"><div class="col-md-3">Due Date : </div><div class="col-md-3">{% if item.duedate != none %}{{ item.duedate }}{% else %} - {% endif %}</div></div>
                <div class="row"><div class="col-md-3">Maker : </div><div class="col-md-3">{{ data.maker }} </div></div>
                <div class="row"><div class="col-md-3">Duration : </div><div class="col-md-3">{{ data.duration }} minutes</div></div>
                <div class="row"><div class="col-md-3">Rating : </div><div class="col-md-3">{{ data.get_rating_display }} </div></div>
            </p>
        {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/forgot.html
{% extends 'libapp/base.html' %}
{% block title %}
    Forgot Password
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        {% if msg != '' %}
        <div class="alert alert-danger alert-dismissable">
            {{ msg }}
        </div>
        {% endif %}
        <fieldset style="padding-top: 20px;position: relative;top: 10px">
            <legend>Forgot Password</legend>
            <form action="" method="post">
                {% csrf_token %}

                <div class="form-group">
                    Username: {{ form.username }}
                </div>

                <div class="form-group">

                        <input type="submit" value="Send Mail" class="btn btn-danger">

                </div>

            </form>
        </fieldset>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/index.html
{% extends 'libapp/base.html' %}
{% block title %}
    Home
{% endblock %}
{% block body_block %}

    <div class="row bg-info float-right">
        <div class="col-lg-9"></div>
        <div class="col-lg-3">
            Lucky Number :
            {% if request.session.lucky_num %}
            {{ request.session.lucky_num }}
            {% else %} 0
            {% endif %}
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <h2>List of Library items</h2>
        </div>
        <div class="row">
            <div class="panel panel-primary col-sm-5 ">
                <div class="panel-heading">
                    Books
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.itemtype == "Book" %}
                                <li> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
            <div class="panel panel-primary col-sm-5 col-sm-offset-2">
                <div class="panel-heading">
                    DVDs
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.itemtype == "DVD" %}
                            <li> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/index_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if itemlist %}
        <h2>List of Library items</h2>
        <ol>
            {% for item in itemlist %}
                <li> <a href="{% url 'libapp:detail' item.id %}">{{ item}} </a></li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}

    <p><a href="{% url 'libapp:about' %}">About page</a></p>
</body>
</html>

libsite/libapp/templates/libapp/login.html
{% extends 'libapp/base.html' %}
{% block title %}
    Login
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        {% if msg != '' %}
        <div class="alert alert-danger alert-dismissable">
            {{ msg }}
        </div>
        {% endif %}
        <fieldset style="padding-top: 20px;position: relative;top: 10px">
            <legend>Welcome</legend>
            <form action="{% url 'libapp:login' %}" method="post">
                {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>

                    <div class="form-group">

                            <input type="submit" value="Login" class="btn btn-danger">
                            <a href="{% url 'libapp:forgot' %}" class="btn btn-warning">Forgot password</a>

                    </div>

            </form>
        </fieldset>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/newitem.html
{% extends 'libapp/base.html' %}
{% block title %}
    New Item
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        <div class="row h2">
            List of Suggested items
        </div>
        <div class="row">
            <div class="panel panel-primary col-sm-5 ">
                <div class="panel-heading">
                    Books
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.get_type_display == "Book" %}
                                <li>{{ item.title}} - {{ item.pubyr }} - ${{ item.cost }}</li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
            <div class="panel panel-primary col-sm-5 col-sm-offset-2">
                <div class="panel-heading">
                    DVDs
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.get_type_display == "DVD" %}
                                <li>{{ item.title}} - {{ item.pubyr }} - ${{ item.cost }}</li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row h2">
            <h2>You can suggest a new item for purchase here.</h2>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="panel panel-primary col-sm-6 ">
                <div class="panel-heading">
                    New Item
                </div>
                <div class="panel-body" style="padding: 10px">
                    <form action="{% url 'libapp:newitem' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <input type="submit" value="Submit" class="btn btn-success col-md-4 col-md-offset-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/searchlib.html
{% extends 'libapp/base.html' %}
{% block title %}
    Suggestions
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        <div class="panel panel-danger col-md-12">
            <div class="panel-heading">Search</div>
            <div class="panel-body">
                <form action="(% url 'libapp:searchlib %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="btn btn-success" type="submit" value="Search">
                </form>
            </div>
        </div>
        <div class="row h2">
            List of Searched items
        </div>
        <div class="row">
            <div class="panel panel-primary col-sm-5 ">
                <div class="panel-heading">
                    Books
                </div>
                <div class="panel-body">
                    {% if booklist %}
                    <ol>
                        {% for item in booklist %}
                            {% if item.itemtype == "Book" %}
                                <li> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a> <br/> Author : {{ item.author }}</li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
            <div class="panel panel-primary col-sm-5 col-sm-offset-2">
                <div class="panel-heading">
                    DVDs
                </div>
                <div class="panel-body">
                    {% if dvdlist %}
                    <ol>
                        {% for item in dvdlist %}
                            {% if item.itemtype == "DVD" %}
                            <li> <a href="{% url 'libapp:detail' item.id %}">{{ item.title}} </a> <br/> Maker : {{ item.maker }}</li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

libsite/libapp/templates/libapp/suggestions.html
{% extends 'libapp/base.html' %}
{% block title %}
    Suggestions
{% endblock %}
{% block body_block %}

    <div class="container-fluid">
        <div class="row h2">
            List of Suggested items
            <span style="float: right"><a href="{% url 'libapp:newitem' %}" class="btn btn-success">New Item</a></span>
        </div>
        <div class="row">
            <div class="panel panel-primary col-sm-5 ">
                <div class="panel-heading">
                    Books
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.get_type_display == "Book" %}
                                <li><a href="/libapp/suggestion/{{ item.id }}">{{ item.title}}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
            <div class="panel panel-primary col-sm-5 col-sm-offset-2">
                <div class="panel-heading">
                    DVDs
                </div>
                <div class="panel-body">
                    {% if itemlist %}
                    <ol>
                        {% for item in itemlist %}
                            {% if item.get_type_display == "DVD" %}
                                <li><a href="/libapp/suggestion/{{ item.id }}">{{ item.title}}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>

                    {% else %}
                        <strong>There are no available items!</strong>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}